<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'
  import { locale, translate } from '../../stores/locale'
  const t = translate
  $: currentLocale = $locale
</script>

<section id="cta" data-locale={currentLocale} class="py-16 px-4 bg-white dark:bg-surface-900 scroll-mt-24"><div class="max-w-7xl mx-auto"><div class="rounded-3xl border border-surface-200 dark:border-surface-800 bg-gradient-to-r from-theme-primary/10 via-indigo-500/10 to-cyan-500/10 p-10 overflow-hidden relative"><div class="absolute -top-20 -right-20 w-72 h-72 rounded-full bg-theme-primary/20 blur-3xl"></div><div class="absolute -bottom-24 -left-24 w-72 h-72 rounded-full bg-indigo-500/20 blur-3xl"></div><div class="relative grid grid-cols-1 lg:grid-cols-12 gap-10 items-center"><div class="lg:col-span-7"><h2 class="heading-2 text-secondary-900 dark:text-white">{t('landing.cta.title')}</h2><p class="text-body text-secondary-600 dark:text-secondary-400 mt-3 max-w-2xl">{t('landing.cta.subtitle')}</p><div class="mt-7 flex flex-col sm:flex-row gap-4"><a href="/auth/register" class="btn-theme-primary px-8 py-4 rounded-xl font-semibold inline-flex items-center justify-center gap-2">{t('landing.cta.primary')}<Icon icon={Icons.arrowRight} className="w-5 h-5" /></a><a href="/dashboard" class="px-8 py-4 rounded-xl font-semibold border border-surface-200 dark:border-surface-800 bg-white/80 dark:bg-surface-900/70 hover:border-theme-primary transition-colors text-secondary-900 dark:text-white text-center">{t('landing.cta.secondary')}</a></div></div><div class="lg:col-span-5"><div class="rounded-2xl bg-white/70 dark:bg-surface-900/70 border border-surface-200 dark:border-surface-800 p-6"><p class="text-sm font-semibold text-secondary-900 dark:text-white">{t('landing.cta.highlights.title')}</p><ul class="mt-4 space-y-3 text-sm text-secondary-700 dark:text-secondary-200">{#each ['forms','tables','charts'] as item}<li class="flex items-center justify-between"><span>{t(`landing.cta.highlights.items.${item}`)}</span><span class="px-2 py-0.5 rounded-full bg-theme-primary/10 text-theme-primary text-xs font-semibold">{t('landing.cta.highlights.ready')}</span></li>{/each}</ul></div></div></div></div></div></section>
