<script lang="ts">
  import Logo from '../common/Logo.svelte'
  import { locale, translate } from '../../stores/locale'
  const t = translate
  $: currentLocale = $locale
  $: year = new Date().getFullYear()
</script>

<footer data-locale={currentLocale} class="px-4 py-12 bg-surface-50 dark:bg-surface-950 border-t border-surface-200 dark:border-surface-800"><div class="max-w-7xl mx-auto"><div class="grid grid-cols-1 md:grid-cols-12 gap-10"><div class="md:col-span-4"><a href="/" class="inline-block hover:opacity-80 transition-opacity"><Logo width={140} height={28} /></a><p class="text-sm text-secondary-600 dark:text-secondary-400 mt-4 max-w-sm">{t('landing.footer.description')}</p></div><div class="md:col-span-8 grid grid-cols-2 sm:grid-cols-3 gap-8"><div><p class="text-sm font-semibold text-secondary-900 dark:text-white">{t('landing.footer.product')}</p><div class="mt-3 space-y-2 text-sm"><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/dashboard">{t('landing.footer.links.live_demo')}</a><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/charts/line">{t('nav.charts')}</a><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/tables/data">{t('header.components.tables')}</a></div></div><div><p class="text-sm font-semibold text-secondary-900 dark:text-white">{t('landing.footer.pages')}</p><div class="mt-3 space-y-2 text-sm"><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/pages/pricing">{t('pages.pricing')}</a><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/pages/account-settings">{t('pages.account_settings')}</a><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/pages/faq">{t('pages.faq')}</a></div></div><div><p class="text-sm font-semibold text-secondary-900 dark:text-white">{t('landing.footer.auth')}</p><div class="mt-3 space-y-2 text-sm"><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/auth/login">{t('landing.footer.links.login')}</a><a class="block text-secondary-600 dark:text-secondary-400 hover:text-secondary-900 dark:hover:text-white" href="/auth/register">{t('landing.footer.links.register')}</a></div></div></div></div><div class="mt-10 pt-8 border-t border-surface-200 dark:border-surface-800 flex flex-col sm:flex-row justify-center gap-4"><p class="text-sm text-secondary-500 dark:text-secondary-400">{t('landing.footer.copyright', { year })}</p></div></div></footer>
