<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'
  import { locale, translate } from '../../stores/locale'

  const t = translate
  $: currentLocale = $locale
  const plans = [
    { name: 'landing.pricing.plans.starter.name', price: '$9', description: 'landing.pricing.plans.starter.description', popular: false, features: [['landing.pricing.features.team_members_5', true], ['landing.pricing.features.storage_10gb', true], ['landing.pricing.features.basic_analytics', true], ['landing.pricing.features.email_support', true], ['landing.pricing.features.custom_domain', false], ['landing.pricing.features.advanced_analytics', false], ['landing.pricing.features.priority_support', false], ['landing.pricing.features.api_access', false]] },
    { name: 'landing.pricing.plans.professional.name', price: '$29', description: 'landing.pricing.plans.professional.description', popular: true, features: [['landing.pricing.features.team_members_25', true], ['landing.pricing.features.storage_100gb', true], ['landing.pricing.features.advanced_analytics', true], ['landing.pricing.features.priority_email_support', true], ['landing.pricing.features.custom_domain', true], ['landing.pricing.features.api_access', true], ['landing.pricing.features.phone_support_24_7', false], ['landing.pricing.features.dedicated_manager', false]] },
    { name: 'landing.pricing.plans.enterprise.name', price: '$99', description: 'landing.pricing.plans.enterprise.description', popular: false, features: [['landing.pricing.features.team_members_unlimited', true], ['landing.pricing.features.storage_unlimited', true], ['landing.pricing.features.advanced_reporting', true], ['landing.pricing.features.support_24_7_phone_email', true], ['landing.pricing.features.custom_branding', true], ['landing.pricing.features.api_access_full', true], ['landing.pricing.features.dedicated_account_manager', true], ['landing.pricing.features.custom_integrations', true]] },
  ] as const
</script>

<section id="pricing" data-locale={currentLocale} class="py-24 px-4 bg-surface-50 dark:bg-surface-950 scroll-mt-24 relative overflow-hidden">
  <div class="max-w-7xl mx-auto relative z-10"><div class="text-center mb-20"><div class="inline-flex items-center gap-2 py-1.5 px-4 rounded-full bg-white dark:bg-surface-900 border border-surface-200 dark:border-surface-800 shadow-sm mb-6"><span class="relative flex h-2 w-2"><span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-theme-primary opacity-75"></span><span class="relative inline-flex rounded-full h-2 w-2 bg-theme-primary"></span></span><span class="text-sm font-semibold text-secondary-600 dark:text-secondary-300">{t('landing.pricing.badge')}</span></div><h2 class="text-display-section text-secondary-900 dark:text-white mb-6">{t('landing.pricing.title_prefix')} <span class="text-gradient">{t('landing.pricing.title_emphasis')}</span></h2><p class="text-lead text-secondary-600 dark:text-secondary-400 max-w-2xl mx-auto">{t('landing.pricing.subtitle')}</p></div>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
      {#each plans as plan}<div class={`relative rounded-[2rem] p-8 flex flex-col transition-all duration-300 ${plan.popular ? 'bg-white dark:bg-surface-900 shadow-2xl shadow-theme-primary/10 border-2 border-theme-primary scale-105 z-10' : 'bg-surface-50 dark:bg-surface-950 border border-surface-200 dark:border-surface-800 hover:border-theme-primary/30 hover:shadow-xl'}`}>{#if plan.popular}<div class="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-theme-primary text-white px-4 py-1 rounded-full text-sm font-bold shadow-lg shadow-theme-primary/20">{t('landing.pricing.most_popular')}</div>{/if}<div class="mb-8"><h3 class="heading-5 text-secondary-900 dark:text-white mb-2">{t(plan.name)}</h3><p class="text-body-sm text-secondary-500 dark:text-secondary-400 h-10">{t(plan.description)}</p></div><div class="mb-8"><div class="flex items-baseline"><span class="text-display-price text-secondary-900 dark:text-white tracking-tight">{plan.price}</span><span class="text-body-sm text-secondary-500 dark:text-secondary-400 ml-2">{t('landing.pricing.period.per_month')}</span></div></div><div class="flex-grow space-y-4 mb-8">{#each plan.features as feature}<div class="flex items-center gap-3">{#if feature[1]}<div class="w-6 h-6 rounded-full bg-theme-primary/10 flex items-center justify-center flex-shrink-0"><Icon icon={Icons.check} className="w-4 h-4 text-theme-primary" /></div>{:else}<div class="w-6 h-6 rounded-full bg-surface-200 dark:bg-surface-800 flex items-center justify-center flex-shrink-0"><Icon icon={Icons.x} className="w-4 h-4 text-secondary-400 dark:text-secondary-600" /></div>{/if}<span class={`text-sm ${feature[1] ? 'text-secondary-700 dark:text-secondary-300 font-medium' : 'text-secondary-400 dark:text-secondary-600'}`}>{t(feature[0])}</span></div>{/each}</div><a href="/auth/register" class={`w-full py-4 rounded-xl font-bold transition-all duration-200 text-center ${plan.popular ? 'bg-theme-primary text-white hover:brightness-90 shadow-lg shadow-theme-primary/25 hover:shadow-theme-primary/40' : 'bg-white dark:bg-surface-800 text-secondary-900 dark:text-white border border-surface-200 dark:border-surface-700 hover:bg-surface-50 dark:hover:bg-surface-700'}`}>{t('landing.pricing.cta.get_started')}</a></div>{/each}
    </div>
  </div>
</section>
