<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'

  type ViewMode = 'designer' | 'instances' | 'approvals' | 'analytics'
  let viewMode: ViewMode = 'designer'
  let machines: string[] = []
  let selectedMachine = ''
  let showTemplates = false

  function createMachine(): void { machines = [...machines, `New State Machine ${machines.length + 1}`]; selectedMachine = machines[machines.length - 1] }
</script>
<div class="space-y-6 animate-fade-in">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-emerald-100 dark:bg-emerald-900/40 flex items-center justify-center"><Icon icon="solar:check-square-bold" className="w-5 h-5 text-emerald-600 dark:text-emerald-400" /></div><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">Approval Engine</h1><p class="text-sm text-gray-500 dark:text-gray-400">State machine-based approval workflows</p></div></div></div></div>
  <div class="bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-900/20 dark:to-teal-900/20 rounded-xl p-6 border border-emerald-200 dark:border-emerald-800"><h3 class="text-sm font-semibold text-emerald-900 dark:text-emerald-100 mb-1">Advanced Complex Logic</h3><p class="text-sm text-emerald-700 dark:text-emerald-300 mb-4">Implement sophisticated approval workflows with multi-level hierarchies, conditional routing, and comprehensive audit trails. Perfect for enterprise-grade approval processes.</p><div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div class="flex items-center gap-2 text-sm text-emerald-800 dark:text-emerald-200"><Icon icon="solar:users-group-rounded-bold" className="w-4 h-4" />Multi-level Approvals</div><div class="flex items-center gap-2 text-sm text-emerald-800 dark:text-emerald-200"><Icon icon="solar:branching-paths-up-bold" className="w-4 h-4" />Conditional Routing</div><div class="flex items-center gap-2 text-sm text-emerald-800 dark:text-emerald-200"><Icon icon="solar:history-bold" className="w-4 h-4" />Audit Trail</div><div class="flex items-center gap-2 text-sm text-emerald-800 dark:text-emerald-200"><Icon icon="solar:alarm-bold" className="w-4 h-4" />Auto Escalation</div></div></div>

  <div class="flex flex-col h-full min-h-[700px]">
    <div class="flex items-center justify-between p-4 border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800"><div class="flex items-center gap-4"><div class="flex items-center gap-3"><div class="p-2 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600"><Icon icon="solar:diagram-down-bold" className="w-6 h-6 text-white" /></div><div><h1 class="text-lg font-bold text-slate-800 dark:text-white">State Machine &amp; Approvals</h1><p class="text-sm text-slate-500 dark:text-slate-400">Design workflows and manage approvals</p></div></div></div><div class="flex rounded-lg bg-slate-100 dark:bg-slate-700 p-1">{#each ['designer','instances','approvals','analytics'] as mode}<button type="button" on:click={() => (viewMode = mode as ViewMode)} class={`px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2 ${viewMode === mode ? 'bg-white dark:bg-slate-600 text-slate-800 dark:text-white shadow-sm' : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white'}`}><Icon icon={mode === 'designer' ? 'solar:pen-new-square-bold' : mode === 'instances' ? 'solar:layers-bold' : mode === 'approvals' ? 'solar:clipboard-check-bold' : 'solar:chart-bold'} className="w-4 h-4" />{mode.charAt(0).toUpperCase() + mode.slice(1)}{#if mode === 'approvals' && machines.length > 0}<span class="px-1.5 py-0.5 rounded-full bg-amber-500 text-white text-xs">{machines.length}</span>{/if}</button>{/each}</div></div>
    <div class="flex flex-1 overflow-hidden"><div class="w-64 border-r border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-y-auto"><div class="p-4"><div class="flex items-center justify-between mb-4"><h2 class="text-sm font-semibold text-slate-800 dark:text-slate-200">State Machines</h2><div class="flex gap-1"><button type="button" on:click={() => (showTemplates = true)} class="p-1.5 rounded-lg hover:bg-slate-100 text-slate-600" title="From template"><Icon icon="solar:copy-bold" className="w-4 h-4" /></button><button type="button" on:click={createMachine} class="p-1.5 rounded-lg hover:bg-slate-100 text-slate-600" title="New machine"><Icon icon="solar:add-circle-bold" className="w-4 h-4" /></button></div></div>{#if machines.length === 0}<div class="text-center py-8 text-slate-500 dark:text-slate-400"><Icon icon="solar:diagram-down-bold" className="w-10 h-10 mx-auto mb-2 opacity-30" /><p class="text-sm">No state machines yet</p><button type="button" on:click={() => (showTemplates = true)} class="mt-2 text-sm text-indigo-600 dark:text-indigo-400 hover:underline">Start from template</button></div>{:else}<div class="space-y-2">{#each machines as machine}<button type="button" on:click={() => (selectedMachine = machine)} class={`w-full p-3 rounded-lg text-left transition-colors ${selectedMachine === machine ? 'bg-indigo-50 border border-indigo-200' : 'hover:bg-slate-50 border border-transparent'}`}><div class="flex items-center gap-2 mb-1"><Icon icon="solar:diagram-down-bold" className="w-4 h-4 text-indigo-600" /><span class="font-medium text-slate-800 truncate">{machine}</span></div><div class="flex items-center gap-3 text-xs text-slate-500"><span>0 states</span><span>0 transitions</span></div></button>{/each}</div>{/if}</div></div><div class="flex-1 flex overflow-hidden">{#if selectedMachine}<div class="flex-1 relative bg-slate-50 dark:bg-slate-900"><div class="absolute top-4 left-4 z-10 flex gap-2"><button type="button" class="flex items-center gap-2 px-3 py-2 rounded-lg bg-white shadow-md"><Icon icon={Icons.plus} className="w-4 h-4 text-indigo-600" />Add State</button><button type="button" class="flex items-center gap-2 px-3 py-2 rounded-lg bg-white shadow-md"><Icon icon={Icons.check} className="w-4 h-4 text-green-600" />Validate</button></div></div>{:else}<div class="flex-1 flex items-center justify-center text-slate-500 dark:text-slate-400"><div class="text-center"><Icon icon="solar:diagram-down-bold" className="w-12 h-12 mx-auto mb-3 opacity-30" /><p class="text-base font-medium">Select a state machine</p><p class="text-sm">Or create a new one to get started</p></div></div>{/if}</div></div>
  </div>
  {#if showTemplates}<div class="fixed inset-0 z-[1050] flex items-center justify-center p-4"><button type="button" class="absolute inset-0 bg-black/50 backdrop-blur-sm" aria-label="Close templates" on:click={() => (showTemplates = false)}></button><div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6"><div class="flex items-center justify-between"><h3 class="text-lg font-semibold">State Machine Templates</h3><button type="button" on:click={() => (showTemplates = false)}><Icon icon={Icons.close} /></button></div><p class="text-sm text-secondary-500 mt-4">Choose a template to start an approval workflow.</p><button type="button" on:click={() => { createMachine(); showTemplates = false }} class="btn-theme-primary px-4 py-2 rounded-lg mt-6">Create from template</button></div></div>{/if}
</div>




