<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'

  let isRunning = false
  let tickCount = 0
  let showAddStream = false
  let showAnomalies = false
  let showMovingAverage = false
  let showBollingerBands = false

  function start(): void { isRunning = true }
  function stop(): void { isRunning = false }
  function reset(): void { isRunning = false; tickCount = 0 }
</script>
<div class="space-y-6 animate-fade-in">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
    <div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-success-100 dark:bg-success-900/40 flex items-center justify-center"><Icon icon={Icons.simulation} className="w-5 h-5 text-success-600 dark:text-success-400" /></div><div><div class="flex items-center gap-2"><h1 class="heading-2 text-secondary-900 dark:text-white">Real-Time Simulation</h1><span class="flex items-center gap-1 text-xs font-medium text-success-600 bg-success-100 dark:bg-success-900/30 px-2 py-0.5 rounded-full"><Icon icon={Icons.circleFilled} className="w-1.5 h-1.5 animate-pulse" />Live</span></div><p class="text-body-sm text-secondary-500 dark:text-secondary-400 mt-0.5">Live data streaming with anomaly detection and statistical analysis</p></div></div></div>
    <div class="flex items-center gap-2"><span class="px-3 py-1.5 rounded-lg bg-surface-100 dark:bg-surface-800 text-xs font-medium text-secondary-600 dark:text-secondary-400">Anomaly Detection</span><span class="px-3 py-1.5 rounded-lg bg-surface-100 dark:bg-surface-800 text-xs font-medium text-secondary-600 dark:text-secondary-400">Statistics</span></div>
  </div>

  <div class="space-y-6">
    <div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 overflow-hidden">
      <div class="px-6 py-5 bg-gradient-to-r from-primary-500 to-accent-500"><div class="flex items-center justify-between"><div class="flex items-center gap-3"><div class="p-2.5 bg-white/20 backdrop-blur-sm rounded-xl"><Icon icon="solar:graph-up-linear" className="w-6 h-6 text-white" /></div><div><h1 class="text-xl font-bold text-white">Real-Time Simulation</h1><p class="text-sm text-white/80">{isRunning ? `Running · ${tickCount.toLocaleString()} ticks · 0 streams` : 'Configure and start data streams'}</p></div></div><div class="flex items-center gap-3"><div class="flex items-center gap-1 bg-white/10 rounded-lg p-1"><button type="button" on:click={() => (showMovingAverage = !showMovingAverage)} class={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${showMovingAverage ? 'bg-white text-primary-600' : 'text-white/80 hover:bg-white/10'}`}>MA</button><button type="button" on:click={() => (showBollingerBands = !showBollingerBands)} class={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${showBollingerBands ? 'bg-white text-primary-600' : 'text-white/80 hover:bg-white/10'}`}>BB</button></div><button type="button" on:click={start} disabled class="flex items-center gap-2 px-5 py-2.5 bg-white text-primary-600 font-semibold rounded-lg hover:bg-white/90 transition-colors shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"><Icon icon="solar:play-linear" className="w-5 h-5" />Start</button><button type="button" on:click={reset} title="Reset" class="p-2.5 text-white/80 hover:text-white hover:bg-white/10 rounded-lg transition-colors"><Icon icon="solar:refresh-linear" className="w-5 h-5" /></button></div></div></div>
      <div class="grid grid-cols-4 divide-x divide-surface-200 dark:divide-surface-700"><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-secondary-900 dark:text-white">0</p><p class="text-sm text-secondary-500">Active Streams</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-secondary-900 dark:text-white">{tickCount.toLocaleString()}</p><p class="text-sm text-secondary-500">Data Points</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-secondary-900 dark:text-white">0</p><p class="text-sm text-secondary-500">Anomalies Detected</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-secondary-400">{isRunning ? 'Active' : 'Stopped'}</p><p class="text-sm text-secondary-500">Status</p></div></div>
    </div>
    {#if showAnomalies}<div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 overflow-hidden"><div class="px-5 py-4 border-b border-surface-200 flex items-center justify-between"><h3 class="font-semibold">Recent Anomalies</h3><button type="button" on:click={() => (showAnomalies = false)} class="text-sm text-primary-600">Acknowledge All</button></div></div>{/if}
    <div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 p-12 text-center"><div class="max-w-md mx-auto"><div class="w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-primary-100 to-accent-100 dark:from-primary-900/30 dark:to-accent-900/30 flex items-center justify-center"><Icon icon="solar:chart-2-linear" className="w-8 h-8 text-primary-500" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">No Data Streams</h3><p class="text-secondary-500 mb-6">Add a data stream to start visualizing real-time data with live updates, anomaly detection, and statistical analysis.</p><button type="button" on:click={() => (showAddStream = true)} class="inline-flex items-center gap-2 px-5 py-2.5 bg-primary-500 text-white font-semibold rounded-xl hover:bg-primary-600 transition-colors"><Icon icon="solar:add-circle-linear" className="w-5 h-5" />Add Your First Stream</button></div></div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    <div class="card rounded-xl p-6"><div class="w-12 h-12 rounded-xl bg-success-100 dark:bg-success-900/40 flex items-center justify-center mb-4"><Icon icon={Icons.activity} className="w-6 h-6 text-success-600 dark:text-success-400" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">Live Data Streams</h3><p class="text-sm text-secondary-500 dark:text-secondary-400">Multiple configurable data streams with realistic patterns and noise simulation.</p></div>
    <div class="card rounded-xl p-6"><div class="w-12 h-12 rounded-xl bg-warning-100 dark:bg-warning-900/40 flex items-center justify-center mb-4"><Icon icon={Icons.alertTriangle} className="w-6 h-6 text-warning-600 dark:text-warning-400" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">Anomaly Detection</h3><p class="text-sm text-secondary-500 dark:text-secondary-400">Advanced algorithms detect anomalies using Bollinger Bands and statistical thresholds.</p></div>
    <div class="card rounded-xl p-6"><div class="w-12 h-12 rounded-xl bg-info-100 dark:bg-info-900/40 flex items-center justify-center mb-4"><Icon icon={Icons.chartLine} className="w-6 h-6 text-info-600 dark:text-info-400" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">Statistical Analysis</h3><p class="text-sm text-secondary-500 dark:text-secondary-400">Real-time calculation of min, max, mean, standard deviation, and moving averages.</p></div>
    <div class="card rounded-xl p-6"><div class="w-12 h-12 rounded-xl bg-primary-100 dark:bg-primary-900/40 flex items-center justify-center mb-4"><Icon icon={Icons.settings} className="w-6 h-6 text-primary-600 dark:text-primary-400" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">Stream Presets</h3><p class="text-sm text-secondary-500 dark:text-secondary-400">Pre-configured streams for CPU, Memory, Network, Sales, and Temperature monitoring.</p></div>
  </div>

  <div class="card rounded-xl overflow-hidden"><div class="px-6 py-4 border-b border-surface-200 dark:border-surface-700"><h3 class="text-lg font-semibold text-secondary-900 dark:text-white flex items-center gap-2"><Icon icon={Icons.code} className="w-5 h-5 text-secondary-500" />Technical Implementation</h3></div><div class="p-6"><div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div><h4 class="font-medium text-secondary-900 dark:text-white mb-3">Data Generation</h4><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-success-500" />Configurable interval timing (100ms - 5s)</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-success-500" />Base value with random noise injection</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-success-500" />Trend simulation (random walk)</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-success-500" />Min/max value bounds</li></ul></div><div><h4 class="font-medium text-secondary-900 dark:text-white mb-3">Analysis Features</h4><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-info-500" />Moving average (configurable window)</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-info-500" />Bollinger Bands calculation</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-info-500" />Standard deviation tracking</li><li class="flex items-center gap-2"><Icon icon={Icons.circleCheck} className="w-4 h-4 text-info-500" />Z-score anomaly detection</li></ul></div></div></div></div>
</div>
