<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'
  import { projectTemplates } from '../../../features/task-scheduler/config'

  type ViewMode = 'dashboard' | 'gantt' | 'calendar' | 'dependencies'
  let viewMode: ViewMode = 'dashboard'
  let showAddTask = false
  let taskName = ''
  let taskCount = 0

  function addTask(): void { if (taskName.trim()) { taskCount += 1; taskName = ''; showAddTask = false } }
</script>
<div class="space-y-6 animate-fade-in">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-900/40 flex items-center justify-center"><Icon icon="solar:calendar-bold" className="w-5 h-5 text-blue-600 dark:text-blue-400" /></div><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">Task Scheduler</h1><p class="text-sm text-gray-500 dark:text-gray-400">Intelligent task scheduling with dependencies</p></div></div></div></div>
  <div class="bg-gradient-to-r from-blue-50 to-cyan-50 dark:from-blue-900/20 dark:to-cyan-900/20 rounded-xl p-6 border border-blue-200 dark:border-blue-800"><h3 class="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-1">Advanced Complex Logic</h3><p class="text-sm text-blue-700 dark:text-blue-300 mb-4">Advanced task management with dependency tracking, Gantt chart visualization, critical path analysis, and intelligent scheduling algorithms.</p><div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div class="flex items-center gap-2 text-sm text-blue-800 dark:text-blue-200"><Icon icon="solar:chart-2-bold" className="w-4 h-4" />Gantt Charts</div><div class="flex items-center gap-2 text-sm text-blue-800 dark:text-blue-200"><Icon icon="solar:link-bold" className="w-4 h-4" />Dependencies</div><div class="flex items-center gap-2 text-sm text-blue-800 dark:text-blue-200"><Icon icon="solar:route-bold" className="w-4 h-4" />Critical Path</div><div class="flex items-center gap-2 text-sm text-blue-800 dark:text-blue-200"><Icon icon="solar:calendar-mark-bold" className="w-4 h-4" />Calendar View</div></div></div>

  <div class="p-6 space-y-6"><div class="flex items-center justify-between"><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">Task Scheduler</h1><p class="text-gray-500 dark:text-gray-400">Schedule tasks, manage dependencies, and visualize your project timeline</p></div><div class="flex items-center gap-3"><button type="button" class="px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-100 rounded-lg transition-colors flex items-center gap-2"><Icon icon="solar:database-bold" className="w-4 h-4" />Load Sample</button><button type="button" class="px-4 py-2 border border-red-300 dark:border-red-600 text-red-600 dark:text-red-400 hover:bg-red-50 rounded-lg transition-colors flex items-center gap-2"><Icon icon="solar:trash-bin-minimalistic-bold" className="w-4 h-4" />Clear All</button><button type="button" on:click={() => (showAddTask = true)} class="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors flex items-center gap-2"><Icon icon="solar:add-circle-bold" className="w-4 h-4" />Add Task</button></div></div>
    <div class="flex bg-gray-100 dark:bg-gray-700 rounded-lg p-1 w-fit">{#each [{id:'dashboard',label:'Dashboard',icon:'solar:widget-bold-duotone'},{id:'gantt',label:'Gantt',icon:'solar:calendar-bold-duotone'},{id:'calendar',label:'Calendar',icon:'solar:calendar-date-bold-duotone'},{id:'dependencies',label:'Dependencies',icon:'solar:graph-bold-duotone'}] as tab}<button type="button" on:click={() => (viewMode = tab.id as ViewMode)} class={`px-4 py-2 rounded-md flex items-center gap-2 transition-colors ${viewMode === tab.id ? 'bg-white dark:bg-gray-600 text-gray-900 dark:text-white shadow-sm' : 'text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white'}`}><Icon icon={tab.icon} className="w-4 h-4" />{tab.label}</button>{/each}</div>
    {#if viewMode === 'dashboard'}<div class="space-y-6"><div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">{#each [{label:'Total Tasks',value:taskCount,icon:'solar:checklist-minimalistic-bold-duotone',tone:'blue'},{label:'Completed',value:0,icon:'solar:check-circle-bold-duotone',tone:'green'},{label:'In Progress',value:0,icon:'solar:play-circle-bold-duotone',tone:'yellow'},{label:'Blocked',value:0,icon:'solar:lock-bold-duotone',tone:'red'},{label:'Overdue',value:0,icon:'solar:calendar-bold-duotone',tone:'orange'},{label:'Completion Rate',value:'0%',icon:'solar:chart-2-bold-duotone',tone:'purple'}] as stat}<div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4"><div class="flex items-center gap-3"><div class={`p-2 bg-${stat.tone}-100 dark:bg-${stat.tone}-900/30 rounded-lg`}><Icon icon={stat.icon} className={`w-6 h-6 text-${stat.tone}-600`} /></div><div><p class="text-2xl font-bold text-gray-900 dark:text-white">{stat.value}</p><p class="text-sm text-gray-500 dark:text-gray-400">{stat.label}</p></div></div></div>{/each}</div><div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700"><div class="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700"><h3 class="font-semibold text-gray-900 dark:text-white">Tasks</h3><span class="text-sm text-gray-500">{taskCount} tasks</span></div><div class="max-h-[400px] overflow-auto"><div class="p-8 text-center text-gray-500 dark:text-gray-400"><Icon icon="solar:checklist-minimalistic-linear" className="w-12 h-12 mx-auto mb-3 opacity-50" /><p>No tasks yet</p><p class="text-sm">Create a task or load sample data</p></div></div></div><div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4"><h3 class="font-semibold text-gray-900 dark:text-white mb-4">Project Templates</h3><div class="space-y-3">{#each projectTemplates as template}<div class="p-3 border border-gray-200 dark:border-gray-700 rounded-lg hover:bg-gray-50 cursor-pointer transition-colors"><div class="flex items-center gap-2 mb-1"><Icon icon={template.icon} className="w-5 h-5 text-primary-500" /><span class="font-medium text-gray-900 dark:text-white">{template.name}</span></div><p class="text-sm text-gray-500 dark:text-gray-400">{template.description}</p><p class="text-xs text-gray-400 dark:text-gray-500 mt-1">{template.tasks.length} tasks • {template.milestones.length} milestones</p></div>{/each}</div></div></div></div>{:else}<div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-8 text-center text-gray-500">The {viewMode} view is ready for scheduled task data.</div>{/if}
  </div>
  {#if showAddTask}<div class="fixed inset-0 z-[1050] flex items-center justify-center p-4"><button type="button" aria-label="Close add task" class="absolute inset-0 bg-black/50 backdrop-blur-sm" on:click={() => (showAddTask = false)}></button><div class="relative bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-lg"><div class="flex items-center justify-between p-4 border-b border-gray-200"><h3 class="text-lg font-semibold">Add New Task</h3><button type="button" on:click={() => (showAddTask = false)}><Icon icon={Icons.close} /></button></div><div class="p-4"><label class="block text-sm font-medium mb-1" for="task-name">Task Name *</label><input id="task-name" bind:value={taskName} class="w-full px-3 py-2 border border-gray-300 rounded-lg" placeholder="Enter task name" /></div><div class="flex justify-end gap-3 p-4 border-t border-gray-200"><button type="button" on:click={() => (showAddTask = false)} class="px-4 py-2 rounded-lg">Cancel</button><button type="button" on:click={addTask} disabled={!taskName.trim()} class="px-4 py-2 bg-primary-600 text-white rounded-lg disabled:opacity-50">Add Task</button></div></div></div>{/if}
</div>


