<script lang="ts">
  import Icon from '../common/Icon.svelte'
  import { Icons } from '../../icons'

  let showFilters = false
  let searchQuery = ''
  let analyzed = false

  function runAnalysis(): void { analyzed = true }
  function clearFilters(): void { searchQuery = ''; showFilters = false }
</script>
<div class="space-y-6 animate-fade-in">
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
    <div><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-accent-100 dark:bg-accent-900/40 flex items-center justify-center"><Icon icon={Icons.insights} className="w-5 h-5 text-accent-600 dark:text-accent-400" /></div><div><div class="flex items-center gap-2"><h1 class="heading-2 text-secondary-900 dark:text-white">Smart Insights</h1><span class="flex items-center gap-1 text-xs font-medium text-accent-600 bg-accent-100 dark:bg-accent-900/30 px-2 py-0.5 rounded-full"><Icon icon={Icons.sparkles} className="w-3 h-3" />AI Analysis</span></div><p class="text-body-sm text-secondary-500 dark:text-secondary-400 mt-0.5">AI-powered analysis with trend detection and actionable recommendations</p></div></div></div>
    <div class="flex items-center gap-2"><span class="px-3 py-1.5 rounded-lg bg-surface-100 dark:bg-surface-800 text-xs font-medium text-secondary-600 dark:text-secondary-400">Trend Detection</span><span class="px-3 py-1.5 rounded-lg bg-surface-100 dark:bg-surface-800 text-xs font-medium text-secondary-600 dark:text-secondary-400">Anomaly Alerts</span></div>
  </div>

  <div class="space-y-6">
    <div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 overflow-hidden"><div class="px-6 py-5 bg-gradient-to-r from-amber-500 to-orange-500"><div class="flex items-center justify-between"><div class="flex items-center gap-3"><div class="p-2.5 bg-white/20 backdrop-blur-sm rounded-xl"><Icon icon="solar:lightbulb-linear" className="w-6 h-6 text-white" /></div><div><h1 class="text-xl font-bold text-white">Smart Insights</h1><p class="text-sm text-white/80">AI-powered analysis of your data</p></div></div><div class="flex items-center gap-3"><button type="button" on:click={runAnalysis} class="flex items-center gap-2 px-5 py-2.5 bg-white text-amber-600 font-semibold rounded-lg hover:bg-white/90 transition-colors shadow-lg"><Icon icon="solar:magic-stick-3-linear" className="w-5 h-5" />Run Analysis</button><button type="button" title="Export JSON" class="p-2.5 text-white/80 hover:text-white hover:bg-white/10 rounded-lg transition-colors"><Icon icon="solar:download-linear" className="w-5 h-5" /></button></div></div></div><div class="grid grid-cols-5 divide-x divide-surface-200 dark:divide-surface-700"><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-secondary-900 dark:text-white">{analyzed ? 3 : 0}</p><p class="text-sm text-secondary-500">Total Insights</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-blue-600">{analyzed ? 3 : 0}</p><p class="text-sm text-secondary-500">New</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-red-600">0</p><p class="text-sm text-secondary-500">Critical</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-orange-600">0</p><p class="text-sm text-secondary-500">High Priority</p></div><div class="px-6 py-4 text-center"><p class="text-2xl font-bold text-amber-600">{analyzed ? 3 : 0}</p><p class="text-sm text-secondary-500">Actionable</p></div></div></div>
    <div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 p-4"><div class="flex items-center gap-4 flex-wrap"><div class="flex-1 min-w-64 relative"><Icon icon={Icons.search} className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-secondary-400" /><input bind:value={searchQuery} placeholder="Search insights..." class="w-full pl-10 pr-4 py-2.5 rounded-xl border border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-800 text-secondary-900 dark:text-white placeholder-secondary-400 focus:outline-none focus:ring-2 focus:ring-amber-500" /></div><button type="button" on:click={() => (showFilters = !showFilters)} class={`flex items-center gap-2 px-4 py-2.5 rounded-xl border transition-colors ${showFilters ? 'border-amber-500 bg-amber-50 dark:bg-amber-900/20 text-amber-600' : 'border-surface-300 dark:border-surface-600 text-secondary-600 hover:bg-surface-50'}`}><Icon icon={Icons.filter} className="w-5 h-5" />Filters</button>{#if searchQuery}<button type="button" on:click={clearFilters} class="text-sm text-secondary-500 hover:text-secondary-700">Clear filters</button>{/if}<div class="flex items-center gap-2"><button type="button" class="text-sm text-red-500 hover:text-red-700">Clear all</button></div></div>{#if showFilters}<div class="mt-4 pt-4 border-t border-surface-200 dark:border-surface-700 space-y-4"><div><p class="text-sm font-medium text-secondary-700 dark:text-secondary-300 mb-2">Categories</p><div class="flex flex-wrap gap-2"><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">Trends</button><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">Anomalies</button><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">Recommendations</button></div></div><div><p class="text-sm font-medium text-secondary-700 dark:text-secondary-300 mb-2">Priority</p><div class="flex flex-wrap gap-2"><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">Low</button><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">Medium</button><button type="button" class="px-3 py-1.5 rounded-lg text-sm font-medium bg-surface-100 dark:bg-surface-800 text-secondary-600">High</button></div></div></div>{/if}</div>
    {#if analyzed}<div class="grid grid-cols-1 lg:grid-cols-3 gap-4"><div class="bg-white dark:bg-surface-900 rounded-xl shadow-md border border-surface-200 p-4"><p class="font-semibold">Revenue trend detected</p><p class="text-sm text-secondary-500 mt-2">Revenue is trending upward over the selected period.</p></div><div class="bg-white dark:bg-surface-900 rounded-xl shadow-md border border-surface-200 p-4"><p class="font-semibold">Conversion opportunity</p><p class="text-sm text-secondary-500 mt-2">A new optimization recommendation is available.</p></div><div class="bg-white dark:bg-surface-900 rounded-xl shadow-md border border-surface-200 p-4"><p class="font-semibold">Traffic anomaly</p><p class="text-sm text-secondary-500 mt-2">A recent traffic pattern needs review.</p></div></div>{:else}<div class="bg-white dark:bg-surface-900 rounded-2xl shadow-lg border border-surface-200 dark:border-surface-700 p-12 text-center"><div class="max-w-md mx-auto"><div class="w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-amber-100 to-orange-100 dark:from-amber-900/30 dark:to-orange-900/30 flex items-center justify-center"><Icon icon="solar:lightbulb-linear" className="w-8 h-8 text-amber-500" /></div><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-2">No Insights Yet</h3><p class="text-secondary-500 mb-6">Run the analysis to discover trends, anomalies, patterns, and actionable recommendations from your data.</p><button type="button" on:click={runAnalysis} class="inline-flex items-center gap-2 px-5 py-2.5 bg-amber-500 text-white font-semibold rounded-xl hover:bg-amber-600 transition-colors"><Icon icon="solar:magic-stick-3-linear" className="w-5 h-5" />Run Demo Analysis</button></div></div>{/if}
  </div>

  <div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div class="card rounded-xl p-5 hover:shadow-md transition-shadow"><div class="flex items-center gap-3 mb-3"><div class="w-10 h-10 rounded-xl bg-info-100 dark:bg-info-900/40 flex items-center justify-center"><Icon icon={Icons.trendingUp} className="w-5 h-5 text-info-600" /></div><div class="font-semibold text-secondary-900 dark:text-white">Trends</div></div><p class="text-sm text-secondary-500 dark:text-secondary-400">Detect upward/downward trends and growth patterns.</p></div><div class="card rounded-xl p-5 hover:shadow-md transition-shadow"><div class="flex items-center gap-3 mb-3"><div class="w-10 h-10 rounded-xl bg-danger-100 dark:bg-danger-900/40 flex items-center justify-center"><Icon icon={Icons.alertTriangle} className="w-5 h-5 text-danger-600 dark:text-danger-400" /></div><div class="font-semibold text-secondary-900 dark:text-white">Anomalies</div></div><p class="text-sm text-secondary-500 dark:text-secondary-400">Identify unusual patterns and outliers.</p></div><div class="card rounded-xl p-5 hover:shadow-md transition-shadow"><div class="flex items-center gap-3 mb-3"><div class="w-10 h-10 rounded-xl bg-success-100 dark:bg-success-900/40 flex items-center justify-center"><Icon icon={Icons.star} className="w-5 h-5 text-success-600 dark:text-success-400" /></div><div class="font-semibold text-secondary-900 dark:text-white">Opportunities</div></div><p class="text-sm text-secondary-500 dark:text-secondary-400">Discover growth opportunities and optimization.</p></div><div class="card rounded-xl p-5 hover:shadow-md transition-shadow"><div class="flex items-center gap-3 mb-3"><div class="w-10 h-10 rounded-xl bg-primary-100 dark:bg-primary-900/40 flex items-center justify-center"><Icon icon={Icons.chartLine} className="w-5 h-5 text-primary-600" /></div><div class="font-semibold text-secondary-900 dark:text-white">Forecasts</div></div><p class="text-sm text-secondary-500 dark:text-secondary-400">Predict future values based on patterns.</p></div></div>

  <div class="card rounded-xl overflow-hidden"><div class="px-6 py-4 border-b border-surface-200 dark:border-surface-700"><h3 class="text-lg font-semibold text-secondary-900 dark:text-white flex items-center gap-2"><Icon icon={Icons.cpu} className="w-5 h-5 text-secondary-500" />Analysis Algorithms</h3></div><div class="p-6"><div class="grid grid-cols-1 md:grid-cols-3 gap-6"><div><h4 class="font-medium text-secondary-900 dark:text-white mb-3 flex items-center gap-2"><span class="w-6 h-6 rounded-full bg-info-100 dark:bg-info-900/50 flex items-center justify-center text-xs font-bold text-info-600">1</span>Trend Analysis</h4><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-info-500" />Linear regression for trend direction</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-info-500" />Percentage change calculation</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-info-500" />Volatility measurement</li></ul></div><div><h4 class="font-medium text-secondary-900 dark:text-white mb-3 flex items-center gap-2"><span class="w-6 h-6 rounded-full bg-warning-100 dark:bg-warning-900/50 flex items-center justify-center text-xs font-bold text-warning-600">2</span>Anomaly Detection</h4><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-warning-500" />Z-score based outlier detection</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-warning-500" />IQR (Interquartile Range) method</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-warning-500" />Sudden spike/drop detection</li></ul></div><div><h4 class="font-medium text-secondary-900 dark:text-white mb-3 flex items-center gap-2"><span class="w-6 h-6 rounded-full bg-primary-100 dark:bg-primary-900/50 flex items-center justify-center text-xs font-bold text-primary-600">3</span>Forecasting</h4><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-primary-500" />Moving average extrapolation</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-primary-500" />Trend-based projection</li><li class="flex items-start gap-2"><Icon icon={Icons.chevronRight} className="w-4 h-4 mt-0.5 text-primary-500" />Confidence interval estimation</li></ul></div></div></div></div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div class="card rounded-xl p-6"><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-4 flex items-center gap-2"><Icon icon={Icons.shopping} className="w-5 h-5 text-accent-600" />E-commerce Analytics</h3><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li>• Revenue trend analysis and forecasting</li><li>• Conversion rate anomaly detection</li><li>• Cart abandonment pattern recognition</li><li>• Product performance recommendations</li></ul></div><div class="card rounded-xl p-6"><h3 class="text-lg font-semibold text-secondary-900 dark:text-white mb-4 flex items-center gap-2"><Icon icon={Icons.deviceDesktop} className="w-5 h-5 text-info-600" />System Monitoring</h3><ul class="space-y-2 text-sm text-secondary-600 dark:text-secondary-400"><li>• CPU/Memory usage trend tracking</li><li>• Performance degradation alerts</li><li>• Resource utilization optimization</li><li>• Capacity planning insights</li></ul></div></div>
</div>


